### ISSUE TITLE
How to run it in SPV mode?

### ISSUE THREAD

**Issue by ales-tsurko** [bcoin-org/bcoin-docker#8]
I've tried all of these variants in `bcoin.conf`:
```
spv: true
node-spv: true
wallet-spv: true
spv-node: true
spv-wallet: true
```

**Comment by ales-tsurko** [comment]
Nevermind, I've solved it by adding Dockerfile as a build source for the docker-compose' service and changing the `CMD` in the Dockerfile. I have no clue why `spv: true` doesn't work though.

**Comment by pinheadmz** [comment]
I've discovered this as well, `spv: true` doesn't work in a config file, only as a launch argument:
`bcoin --spv`

**Comment by pinheadmz** [comment]
The reason is because there are two different types of node objects: `FullNode` and `SPVNode`, and those objects parse the config file. The parameter `SPV` therefore must be parsed _before_ the rest of the configuration, so the correct object is instantiated. Then `SPVNode` or `FullNode` parses the rest of the config file.
